### ISSUE TITLE
All entities are disabled with config flow non advanced mode

### ISSUE THREAD

**Issue by rautesamtr** [dolezsa/thermal_comfort#108]
## Issue
When using config flow in non advanced mode to set up a config entry all entities are disabled by default.

## What do you expect
All entities to be enabled by default

@IATkachenko could you take a look at this?

**Comment by IATkachenko** [comment]
Sure.

**Comment by bmarty** [comment]
Hello, this issue should be re-opened, I observe it in the latest version 2.2.5.
