### ISSUE TITLE
Thermal Perception strange

### ISSUE THREAD

**Issue by kolins-cz** [dolezsa/thermal_comfort#11]
Hello,
I am using your custom integration for a few months. But I am wondering if **Thermal Perception** is correct.
Almost whole winter it shows "A bit dry for some"
![image](https://user-images.githubusercontent.com/8409715/103517891-268e5600-4e73-11eb-949e-980fa30256eb.png)
At 2.6C and 94% humidity it really does not feel "A bit dry"
Maybe calculation is only appropriate for common room temperature (~19-25C)?

**Comment by rautesamtr** [comment]
The thermal perception is currently based on a simple dew point table e.g. 
![image](https://user-images.githubusercontent.com/1131371/141088562-590f0d0c-0fab-4156-a17d-49500317d3dc.png)

Maybe some other perceptional model would be better?

**Comment by tarheelz** [comment]
Works great.  There is a reason many people complain of dry, itchy skin in the winter.

**Comment by rautesamtr** [comment]
Closing this for now, please open a feature request if you would like to have other perceptual models added.
