### ISSUE TITLE
No 'version' key in the manifest file 

### ISSUE THREAD

**Issue by hqsone** [dolezsa/thermal_comfort#12]
No 'version' key in the manifest file for custom integration 'thermal_comfort'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'thermal_comfort'

**Comment by monotonus** [comment]
+1

@dolezsa : Are you still running this custom integration and will further develop it? Or does somebody have to fork it?

**Comment by dolezsa** [comment]
thanks, manifest updated, now it should be ok.
