### ISSUE TITLE
No 'version' key in the manifest file

### ISSUE THREAD

**Issue by flaektrem** [dolezsa/thermal_comfort#13]
Seeing this in my logs:

```
Logger: homeassistant.loader
Source: loader.py:786
First occurred: 19:41:33 (1 occurrences)
Last logged: 19:41:33

No 'version' key in the manifest file for custom integration 'thermal_comfort'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'thermal_comfort'
```

**Comment by XtacySWAT** [comment]
> Seeing this in my logs:
> 
> ```
> Logger: homeassistant.loader
> Source: loader.py:786
> First occurred: 19:41:33 (1 occurrences)
> Last logged: 19:41:33
> 
> No 'version' key in the manifest file for custom integration 'thermal_comfort'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'thermal_comfort'
> ```

Hi,

you'll notice the manifest.json file was edited a month before you posted this, which includes the version line and removes that error.

**Comment by flaektrem** [comment]
> 
> 
> > Seeing this in my logs:
> > ```
> > Logger: homeassistant.loader
> > Source: loader.py:786
> > First occurred: 19:41:33 (1 occurrences)
> > Last logged: 19:41:33
> > 
> > No 'version' key in the manifest file for custom integration 'thermal_comfort'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'thermal_comfort'
> > ```
> 
> Hi,
> 
> you'll notice the manifest.json file was edited a month before you posted this, which includes the version line and removes that error.

Sorry, missed that. I was just waiting for a update in HACS. My bad
