### ISSUE TITLE
Sensors created by config flow don't have underscores in the suffixes

### ISSUE THREAD

**Issue by lymanepp** [dolezsa/thermal_comfort#134]
The sensors created using the config flow don't have underscores in the suffixes like those created using YAML config.
![image](https://user-images.githubusercontent.com/4195527/152666133-25a00df0-e839-4b77-80a5-727ce5be2bbe.png)

**Comment by rautesamtr** [comment]
Sensor created with the yaml config also shouldn't have underscores in their entity id. This was done to keep backwards compatibility.
