### ISSUE TITLE
Improve input sensor selection in config flow

### ISSUE THREAD

**Issue by rautesamtr** [dolezsa/thermal_comfort#135]
The current sensor selection isn't ideal yet especially with a lot of valid entity entries. See #121

Find a better solution.

**Comment by jnxxx** [comment]
It seems like a great integration, but how can I use an attribute as input?

Like this: `state_attr('weather.mylocation', 'humidity')`

**Comment by rautesamtr** [comment]
So revisiting this since we now have [entity selectors](https://www.home-assistant.io/docs/blueprint/selectors/#entity-selector) available for config_flows. Those would resolve #141 with copy pastable id's and offer us text search. So the question remains how much we should still filter the available entities in the list or not.

**Comment by rautesamtr** [comment]
@jnxxx  You can always create template sensors with the attribute as state and use that as input.
