### ISSUE TITLE
UI: Let us copy-paste sensor names

### ISSUE THREAD

**Issue by sevorl** [dolezsa/thermal_comfort#141]
I have loads of sensors. 
When I want to configure the thermal comfort sensor via the UI, I need to scroll through a huge list of sensors to find the correct one.
Would it be possible to type or copy-paste sensor names instead of selecting them from the drop down?

**Comment by rautesamtr** [comment]
See #135 and #121. A possible sollution woul be to add an additional step at the beginning of the config flow which lets you decide between the two selection modes for setting up. On with drop down with only sensors with correct device class and unit of measurement  and one "advanced mode" that let's you manualy input any valid entity id.
We could also only show this extra step if home assistants advanced mode is enabled,

**Comment by rautesamtr** [comment]
This is now possible with 1.5.2 #174
