### ISSUE TITLE
Window Open/Closed detection

### ISSUE THREAD

**Issue by mdeweerd** [dolezsa/thermal_comfort#143]
I think this integration would be a nice location to have open (and closed) window detection.

![image](https://user-images.githubusercontent.com/1504752/155116934-6f1056eb-517b-4d44-a73a-f1caa453127c.png)

I also opened a discussion on the [home assistent forum](https://community.home-assistant.io/t/open-window-detection-based-on-humidity-change-temperature-change/395562).

Some research on the topic: https://onlinelibrary.wiley.com/doi/full/10.1002/2475-8876.12043

**Comment by rautesamtr** [comment]
This is probably to far out of the scope of this integration. Have you tried to implement your idea as template?

**Comment by rautesamtr** [comment]
Closing this for now since like i said this i out of the scope of the integration.
