### ISSUE TITLE
Fahrenheit?

### ISSUE THREAD

**Issue by lotan80** [dolezsa/thermal_comfort#15]
Will the Readme be updated for the latest release? I believe this now includes an option for Fahrenheit, but I do not see any instructions on how to set the temperature unit. Thanks!

**Comment by malcojosh** [comment]
I have the same question. This looks awesome, but it's taking my Fahrenheit inputs and outputting some wonky values, I think because it's treating them as Celsius.

**Comment by cooper7692** [comment]
yeah this would be nice

**Comment by lanarf** [comment]
Same issue; sensors that return data in **Celsius** work fine when passed to Thermal Comfort but passing data from a **Fahrenheit** sensor causes an error (actually just show data not available)
