### ISSUE TITLE
Add enthalpy

### ISSUE THREAD

**Issue by MarkoPaasila** [dolezsa/thermal_comfort#151]
As attribute or separate sensor. That's the only thing missing as far as I'm concerned. Thank you :-)

**Comment by papo-o** [comment]
a python library for enthalpy
http://pyromat.org/

**Comment by rautesamtr** [comment]
There is also [pythermalcomfort](https://github.com/CenterForTheBuiltEnvironment/pythermalcomfort`). I was thinking about to port the relevant code over instead of using it as a dependency since that would bring quite a lot of dependencies with it.

**Comment by rautesamtr** [comment]
closed with #184

**Comment by lymanepp** [comment]
I recently enabled moist air enthalpy sensors. Would it be better if the units were BTU/lb when imperial unit system is active?
