### ISSUE TITLE
Support friendly_name with new 1.5 API

### ISSUE THREAD

**Issue by phbasler** [dolezsa/thermal_comfort#156]
Hi, 

With the new API 1.5 the friendly_name attribute was gone which leads to problems with Umlaute. 
E.g. if I have the sensor 

name: Thermal Comfort Büro
temperature_sensor: sensor.sensor_buero
humidity_sensor: sensor.sensor_buero_2

then the generated sensor name is sensor.thermal_comfort_buro. 
With the old api I could define the sensor name as thermal_comfort_buero and have the "ü" in the friendly_name for the display

It would be nice to have the ability to change the display name to something else, while the new behaviour could still be the default.

**Comment by rautesamtr** [comment]
Wouldn't this issue be solved if core would slugify umlauts to their more readable counterpart when generating the entity id?
https://github.com/home-assistant/core/blob/c8f95b7dfc357480bdf6295b05cf3aba545699ad/homeassistant/helpers/entity_registry.py#L278
https://github.com/home-assistant/core/blob/c8f95b7dfc357480bdf6295b05cf3aba545699ad/homeassistant/util/__init__.py#L45

You also can always use unique_id to modify entity_id and friendly name trough the frontend.

**Comment by rautesamtr** [comment]
https://github.com/home-assistant/core/issues/37139 doesn't look like they are going to change it anytime soon even tough there slugifier has the support to do it https://github.com/un33k/python-slugify/issues/85

With them moving towards autogenerating the enity ids i will close this for now
https://developers.home-assistant.io/blog/2022/07/10/entity_naming/
