### ISSUE TITLE
dumb question about Simmer Index

### ISSUE THREAD

**Issue by bbigras** [dolezsa/thermal_comfort#159]
> An index that combines air temperature and relative humidity. In contrast to the Heat Index it describes the human-perceived equivalent temperature at night and describes a factor of discomfort. 

Does that mean that I should use this index when the sun is down to determine what a comfortable temp/humidity should be, but not during the day?

**Comment by rautesamtr** [comment]
Simmer Index was original implemented by @lymanepp and i used the description from this [site](https://blog.gcwizard.net/manual/de/summer-simmer-index/01-was-ist-der-summer-simmer-index/) which is in German.

Checking again i realize that the only two sources telling it is an index for night time are German. All English ones seem to refer to it as a general indicator for heat stress. Like the [site](http://www.somnwx.com/plugins/bioIndexes/index.php) mentioned in #171.

@lymanepp any clues?

**Comment by rautesamtr** [comment]
Changed the description to reflect that one from #171 and changed the icon to the more generic one.
