### ISSUE TITLE
Problem with Home Assistant 2021.6.3

### ISSUE THREAD

**Issue by Joebinator** [dolezsa/thermal_comfort#16]
Hi there!

Today i have installed Home Assistant 2021.6.3, coming from 2021.5.x and noticed that thermal_comfort is not available anymore.

The Log says: 

_2021-06-09 09:24:56 ERROR (SyncWorker_0) [homeassistant.loader] The custom integration 'thermal_comfort' does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details_

Anyone else having this issue?

PS: Home Assistant Blog reads:

Versions
The second change is pretty cool! Versions!

The manifest.json file now has added support for a version key. The version should be a string with a major, minor and patch version. For example, "1.0.0".

This version will help users communicate with you the version they had issues with. And if you ever find a security issue with your custom integration, Home Assistant will be able to block insecure versions from being used.

**The version key is required from Home Assistant version 2021.6**

**Comment by henneho** [comment]
I had the same issue, but you can add the line
  "version": "1.0.0"
and a "," at the end of the previous line to the manifest.json with the file editor
works fine for me

**Comment by Joebinator** [comment]
> I had the same issue, but you can add the line
> "version": "1.0.0"
> and a "," at the end of the previous line to the manifest.json with the file editor
> works fine for me

WORKED! Thanks @henneho
