### ISSUE TITLE
Had trouble installing - how do I know it has been successful?

### ISSUE THREAD

**Issue by jmichaelp62** [dolezsa/thermal_comfort#160]
I restarted after my last attempt & went to bed. The logs didn't show any error message this time but I don't see the thermal_comfort integration listed anywhere. I have a folder, "/config/custom_components/thermal_comfort/", but the failed installations created that as well.

**Comment by jmichaelp62** [comment]
Hi Gabriel, thanks for the response. I used HACS.

**Comment by rautesamtr** [comment]
Do you get the warning that the integration is being loaded?
```
We found a custom integration thermal_comfort which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
```

**Comment by jmichaelp62** [comment]
Thanks for taking a look at this!

Yes, I did get that warning. When I follow the installation configuration
flow I get error message #1. When I add the example to configuration.yaml I
get error message #2.

#1
[image: image.png]

#2
[image: image.png]

**Comment by rautesamtr** [comment]
Hi @jmichaelp62 sorry to get only back to you now, the images sent trough mail aren't visible here so i can't read error message # 2

**Comment by jmichaelp62** [comment]
The first one is -
Error
This integration does not support configuration via the ui. If you followed
this link from the home assistant website, make sure you run the latest
version of home assistant.
The second one is -
Configuration validation
Validate your configuration if you recently made some changes to it and
want to make sure that it is valid. Configuration invalid! Component error:
thermal_comfort - No module named 'custom_components.thermal_comfort.const'

**Comment by rautesamtr** [comment]
What are your homeassistant, HACS and thermal_comfort versions used?
Could you try the manual installation method?
