### ISSUE TITLE
Platform error sensor.thermal_comfort - No module named 'homeassistant.backports'

### ISSUE THREAD

**Issue by lakee911** [dolezsa/thermal_comfort#175]
Tried installing a new version and went to the latest. After restart, I'm getting the subject error when checking my configuration. Uninstalling does the same thing. Updating does the same thing. I've rolled back about half a dozen times trying to get rid of this.  Can't reboot until I fix it.

Running core-2021.10.6 and trying to get everything up to date before updating the core.

**Comment by rautesamtr** [comment]
Hi the minimum required version for thermal comfort is 2021.12.0 with the current release and will be 2022.4.0 for the next release. It is actually in the hacs.json. I wonder why it doesn't block an update if it isn't met.

**Comment by lakee911** [comment]
So, that's the issue! I went ahead and tried updating the core and nothing
broke (related to hacs and thermal comfort, at least). I was afraid to try
to update thermal comfort now, but seeing as how the issue was an
incompatibility that wasn't blocked, I'll give it a go. I'll be back if
there is another issue. Thanks!
