### ISSUE TITLE
Feature: Add support for HACS

### ISSUE THREAD

**Issue by smolowik** [dolezsa/thermal_comfort#18]
Firstly, installing using HACS is convenient. It will also allow other people to find this custom component faster and easier.

**Comment by alex3305** [comment]
For now you can manually add this repository as a custom repository to HACS for installation and updates.

First go to HACS ➡️ Integrations ➡️ Menu ➡️ Custom repositories

![image](https://user-images.githubusercontent.com/5155694/133907433-7a29b0e6-a6b5-40fb-a7d0-97abd31d248c.png)

You can than add this repo as a custom repository and click the Add button.

![image](https://user-images.githubusercontent.com/5155694/133907469-06f43df2-48d9-45e4-8450-e375736c22b6.png)

After which you can just install **Thermal Comfort** from HACS ❤️.

![image](https://user-images.githubusercontent.com/5155694/133907481-def21936-4d7e-4b20-9afa-249aa27ed0f5.png)
