### ISSUE TITLE
Possible Sensor type renames for 2.0

### ISSUE THREAD

**Issue by rautesamtr** [dolezsa/thermal_comfort#193]
Since we added some new perception/bio-indeces sensors and have a breaking release upcoming it could help to give some of them more distinct names.

The sensors I have in mind:
`Thermal perception` could be renamed to `Dew point perception`.
A bit on the fence regarding this one, but it would make it clearer from where the perception is derived from.

`Simmer index` to `Summer simmer index` and `Simmer zone` to `Summer simmer zone` or `Summer simmer perception`.
This would make it clear, that the index is ment for the Summer.

@dolezsa

**Comment by dolezsa** [comment]
if it breaks people's automations, they won't be happy :D

**Comment by rautesamtr** [comment]
I know there will be people who won't be happy, but 2.0 will break legacy naming anyway since we remove support for the old shortnames and move to the [new naming scheme](https://developers.home-assistant.io/blog/2022/07/10/entity_naming) in core.
