### ISSUE TITLE
Feature: Make decimal accuracy configurable

### ISSUE THREAD

**Issue by mhaas** [dolezsa/thermal_comfort#196]
My temperature and humidity sensors report one digit while the thermal comfort integration provides two digits.

It would be great if I can align the two. I know I can set up a template sensor, but it is quite cumbersome.

![Untitled](https://user-images.githubusercontent.com/260872/188253721-b626e62a-339e-433c-b8bc-d734cb430b3d.png)

**Comment by rautesamtr** [comment]
Core is adding support for [rounding](https://developers.home-assistant.io/blog/2023/01/25/sensor_rounding/). Now the question is how we implement this.

<ol type="a">
<li> Just stick to the 2 decimals for all sensors and let the user override the precision from the frontend.</li>
<li> Set a sensible value for `native_precision` for each sensor. This only makes sense if there is a sensor where the user needs more then 2 decimals.</li>
<li> Make this configurable for all sensors in YAML and frontend.</li>
<li> Make this configurable for each sensors in YAML (making it configurable for each sensor would make configuration rather difficult in the frontend).</li>
</ol>

I'd personally start with `A` and switch to `B` if need arises. I'm not totally against `C` but that would conflict with `B` so it's one or the other.
