### ISSUE TITLE
How is absolute humidity calculated without knowing air pressure?

### ISSUE THREAD

**Issue by scstraus** [dolezsa/thermal_comfort#197]
Hi, I love that this integration exists so thank you for writing it. There's just one thing I'm wondering to give me confidence to use it for my use case. How is the absolute humiditiy calculated if you don't know the air pressure? I was hoping to feed it data from my pressure sensor. Is it just using my home location and getting the air pressure from a weather service or something? Thanks.

**Comment by rautesamtr** [comment]
Currently we just use a default value since air pressure usually doesn't have to much impact on the calculated value. See #2 We can look into it once we add optional inputs like wind speed for wind chill index.

**Comment by scstraus** [comment]
Thanks for the answer. I will keep an eye on #2
