### ISSUE TITLE
Perception No Longer Reports Full Narrative/Friendly State

### ISSUE THREAD

**Issue by tarheelz** [dolezsa/thermal_comfort#219]
Disclaimer: I am sure I am doing something completely dumb.

I have been using Thermal Comfort integration since 2020. In building a new instance of HA, the `state` for `sensor.thermal_comfort_perception` reports simply as “dry” in markdown or developer tools.  The full state, however is "A bit dry for some", which I can see by clicking on info for the sensor.

My first thought was this longer narrative/friendly description had moved to an `attribute` but that is not the case.  My total guess is that “dry” is the simple marker for the icon now being output in the `state` field, which previously had the longer, narrative text.   

Can we get narrative/friendly moved to an `attribute` if not to `state`?

**Comment by rautesamtr** [comment]
That change has been added by supporting translations and is the same as other integration handle this.

**Comment by tarheelz** [comment]
OK.  Thanks.  Do you know how we can now expose the more verbose state in markdown language?  An Entities Card or Glance Card reports the state as "A bit dry for some."  A Markdown Card reports the state as simply "dry."

**Comment by rautesamtr** [comment]
See https://github.com/home-assistant/core/pull/65743

**Comment by rautesamtr** [comment]
Closing this for now as it is a core issue
