### ISSUE TITLE
Invalid config for [sensor.thermal_comfort]: required key not provided

### ISSUE THREAD

**Issue by willemvdvliet** [dolezsa/thermal_comfort#256]
Thermal comfort version: 2.0.1
HA: 2023.1.2

After upgrade/migration from v1.5 > 2.0 I got the error mentioned below.
Tried to remove the Integrations and re-added them again, that was no solution;
Downgraded from v. 2.0.1 to 1.5 the error remains.
Now back again on v2.0.1, but the error remains there.

Error:
Invalid config for [sensor.thermal_comfort]: required key not provided @ data['sensors']['badkamer']['unique_id']. Got None required key not provided @ data['sensors']['gang']['unique_id']. Got None required key not provided @ data['sensors']['gastenkamer']['unique_id']. Got None required key not provided @ data['sensors']['slaapkamer']['unique_id']. Got None required key not provided @ data['sensors']['woonkamer']['unique_id']. Got None. (See /config/sensor.yaml, line 718). Please check the docs at https://github.com/dolezsa/thermal_comfort/blob/master/README.md

**Comment by rautesamtr** [comment]
`unique_id` field is required since [2.0.0](https://github.com/dolezsa/thermal_comfort/releases/tag/2.0.0)
https://github.com/dolezsa/thermal_comfort/blob/2.0/documentation/yaml.md#sensor-options

**Comment by willemvdvliet** [comment]
Did config via frontend not yaml. Just checked it and can't find any reference in config.yaml or sensor.yaml
