### ISSUE TITLE
Dew point is disabled

### ISSUE THREAD

**Issue by B0ndo2** [dolezsa/thermal_comfort#260]
Hi, 
 I have version 1.5.4 and Dew point is disabled, how do I enable it?
Is it possible to have thermal comfort for different areas?

**Comment by rautesamtr** [comment]
Hi, could you provide more information. Did you configure your sensors trough the frontend?
If so you can just add more thermal comforts by just adding it again with + add integration in the Integrations panel. Do you have any warning messages in your logs to know why it is disabled?

**Comment by B0ndo2** [comment]
I did configure them from the frontend.

```2023-01-03 18:11:16.077 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration thermal_comfort which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant```

![image](https://user-images.githubusercontent.com/75389943/212179998-90dbc237-4285-4a1d-bd6e-ccb0cc0fff55.png)

**Comment by rautesamtr** [comment]
Is it possible to enable the sensor in home assistant or is this option grayed out?

**Comment by B0ndo2** [comment]
I was able to enable it, the enable icon isn't really obvious (looks like redo button)
Why was it disabled?

**Comment by rautesamtr** [comment]
Not sure what happened in your case, you are usually able to select the sensors you want to have enabled at the start in the frontend configuratioan dialog and they are all enabled as default.
![image](https://user-images.githubusercontent.com/1131371/212556170-da4f655b-9525-49f0-9d2a-1e5a63088222.png)
