### ISSUE TITLE
Thermal Comfort no longer works with average sensors

### ISSUE THREAD

**Issue by markli96** [dolezsa/thermal_comfort#275]
Hi,

I am using Average Sensor for HA (https://github.com/Limych/ha-average) for calculating average temperatures and humidity in my apartment. For example I am using 4 temperature and humidity sensors to make averages for whole apartment. The sensors are named "sensor.average_indoor_humidity_1_minute" and "sensor.average_indoor_temperature_1_minute", but the HA says they don't have unique ID (https://www.home-assistant.io/faq/unique_id). And then I put them in Thermal Comfort and create "device" (https://prnt.sc/CTl0lX_njBH5).

It was working correctly until last update this morning. But I don't really know when was the last time I updated this addon. Maybe 2 months ago? 

Now it shows "Undefined" for each entity ([https://prnt.sc/oy2XGPXWh5s_](https://prnt.sc/oy2XGPXWh5s_)). The addon is working correctly when it is connected directly to each temperature sensor. But not for average sensors.

Thank you in advance for your help and thank you for this awesome addon, Martin

**Comment by rautesamtr** [comment]
I tried `ha-average` and i can't reproduce the issue. Any other infos in the log?

**Comment by markli96** [comment]
I am so sorry. It was, of course, my fault... In short - I was using bad units.. ("C" instead of "°C")

I am copying the temperature sensor values to helper variable, which I later use, only if the values are valid. Sometimes the sensor sends incorrect values. And then I am using this helper variable in the Average Sensor addon. But I have set the unit as "C" instead of "°C". And "C" is not valid temperature unit.
