### ISSUE TITLE
2023.3.0b0 error

### ISSUE THREAD

**Issue by DavidFW1960** [dolezsa/thermal_comfort#276]
```
Logger: homeassistant.components.sensor
Source: custom_components/thermal_comfort/sensor.py:473
Integration: Sensor (documentation, issues)
First occurred: 9:58:24 AM (1 occurrences)
Last logged: 9:58:24 AM

Error while setting up thermal_comfort platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/thermal_comfort/sensor.py", line 470, in async_setup_entry
    entities: list[SensorThermalComfort] = [
  File "/config/custom_components/thermal_comfort/sensor.py", line 473, in <listcomp>
    entity_description=SensorEntityDescription(**SENSOR_TYPES[sensor_type]),
TypeError: SensorEntityDescription.__init__() got an unexpected keyword argument 'native_precision'
```

**Comment by VDRainer** [comment]
Not sure if that's all, but according to https://developers.home-assistant.io/blog/2023/02/08/sensor_presentation_rounding/ and a little guess :smile: , replacing all `native_precision` with `suggested_display_precision` in sensor.py fixes this for me.

**Comment by DavidFW1960** [comment]
Thanks. Seems to have temporarily fixed it for me

**Comment by VoyteckPL** [comment]
I changed it and it still doesnt work

**Comment by DavidFW1960** [comment]
> I changed it and it still doesnt work

Then you didn't do it right

**Comment by VDRainer** [comment]
> I changed it and it still doesnt work

Only the lower case ones?
![20230224_072852](https://user-images.githubusercontent.com/26381449/221108324-507cebc5-de1b-44f1-b8a7-22b298abfd83.png)
There are 7 in sensor.py

**Comment by VoyteckPL** [comment]
That did the job
