### ISSUE TITLE
native_precision error in HA 2023.3

### ISSUE THREAD

**Issue by pswid** [dolezsa/thermal_comfort#279]
HA 2023.3 (curently beta 2023.3.0b5) shows error in the log. According to [this blog](https://developers.home-assistant.io/blog/2023/02/08/sensor_presentation_rounding/) `native_precision` has been reverted and replaced by `suggested_display_precision`.

Logger: homeassistant.components.sensor
Source: custom_components/thermal_comfort/sensor.py:473
Integration: Sensor ([documentation](https://rc.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 10:20:34 (2 occurrences)
Last logged: 10:20:34

Error while setting up thermal_comfort platform for sensor

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/thermal_comfort/sensor.py", line 470, in async_setup_entry
    entities: list[SensorThermalComfort] = [
  File "/config/custom_components/thermal_comfort/sensor.py", line 473, in <listcomp>
    entity_description=SensorEntityDescription(**SENSOR_TYPES[sensor_type]),
TypeError: SensorEntityDescription.__init__() got an unexpected keyword argument 'native_precision'
```

**Comment by rautesamtr** [comment]
#276 already fixed #278  in master, wait for 2023.3 to be released for the next thermal comfort release since it requires home-assistant >= 2023.3
