### ISSUE TITLE
Not Functioning from Yaml

### ISSUE THREAD

**Issue by Mjohannesson** [dolezsa/thermal_comfort#286]
I have 8 thermal comfort sensors configured in yaml.  They are no longer working.  

The GUI popup is incomplete in english (missing descriptions) and seems to only allow the adding of a single instance of thermal_comfort.

Running 2.1 with latest HA.

This has been going on for a while.  I can't make the new yaml format work.   Even when it passed the config checker it errored out the the "old format in V2 error message"  

Looking for some direction or an example of more than 1 bare-minimum config sensors.

Thanks for this excellent component,  I make significant use of dewpoint and absolute humidity to control my interior humidity with an HRV.

Mark

**Comment by rautesamtr** [comment]
could you post your yaml?

**Comment by Mjohannesson** [comment]
Once I moved the Thermal Comfort instances out of the sensors section of the configuration file it was no longer erroring out.

Then i noticed _dewpoint had been changed to _dew_point, which meant updating template sensors and automations.

Back working now, thanks so much for this component.  Just installing a whole home dehumidifier so I really needed this.

Mark

**Comment by rautesamtr** [comment]
Hi the old configuration format has been deprecated since 2.0
