### ISSUE TITLE
Simple refactor in src.

### ISSUE THREAD

**Issue by RayOfLight1** [dolezsa/thermal_comfort#304]
https://github.com/dolezsa/thermal_comfort/blob/36289926b62805df0e68e1d4643afc1cf2b30f00/custom_components/thermal_comfort/sensor.py#L191C3-L192C38

Hello, can someone refactor all the THEN appearances in sensor.py?

It hurts.

**Comment by rautesamtr** [comment]
Seriously i am ashamed of that typo. If you find any others please report them.
