### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by 8mccm8** [dolezsa/thermal_comfort#329]
Hi all 

in my has:

Home Assistant 2023.8.2
Frontend 20230802.0 - latest

I followed steps to install v2.1.1 and just at this step:
https://github.com/dolezsa/thermal_comfort/blob/master/documentation/config_flow.md#name-your-virtual-device-and-select-the-temperature-and-humidity-sensor-you-want-to-use

this error occurred 

```
Logger: homeassistant.config_entries
Source: config_entries.py:865
First occurred: 04:42:50 (3 occurrences)
Last logged: 04:43:28

Error occurred loading flow for integration thermal_comfort: cannot import name 'ConfigValidationError' from 'homeassistant.exceptions' (/opt/homeassistant/lib/python3.11/site-packages/homeassistant/exceptions.py)
```

thx for your help

**Comment by rautesamtr** [comment]
Hi, this sounds like you installed master instead of 2.1.1.
I forgott to put the new requirements for master in the readme.
It's home assistant 2023.12. To be released in two days.

**Comment by rautesamtr** [comment]
@erikpendragon that would be strange, because we only introduced the import fort `ConfigValidationError` with 65cc554 which is only in master and not 2.1.1. You sure it's not #322 #325 in your case?
 
It's expected that you run into an error with home-assistant 2023.12 running 2.1.1 since core has breaking changes and the fixes are already in master. There will be a release once 2023.12 is out of beta.

**Comment by erikpendragon** [comment]
> @erikpendragon that would be strange, because we only introduced the import fort `ConfigValidationError` with [65cc554](https://github.com/dolezsa/thermal_comfort/commit/65cc5543b538b300569c4ad0adeae7f32e377bb7) which is only in master and not 2.1.1. You sure it's not #322 #325 in your case?
> 
> It's expected that you run into an error with home-assistant 2023.12 running 2.1.1 since core has breaking changes and the fixes are already in master. There will be a release once 2023.12 is out of beta.

[#325](https://github.com/dolezsa/thermal_comfort/issues/325) fixed my issue, thank you

**Comment by 8mccm8** [comment]
@rautesamtr your are right thx
