### ISSUE TITLE
Wrong temperaure on second device

### ISSUE THREAD

**Issue by Gio-dot** [dolezsa/thermal_comfort#339]
Hi, I added two devices in Thermal_comfort: an external temperature sensor and an internal temperature sensor. Ther are no issues with external temperature sensor, but the internal one report wrong temperature and humidity data. Checked several times if i added the right sensor in the integration, and yes, the right sensor is there, but it seems that thermal_cpmfort pick data from an another imaginary sensor... In below screenshots you can see a sensor reporting 22,75°C when the real sensor is at 19,5°C. I also checked the time when source sensor update reading and it is the same of thermal_comfort udate time, but readings are different. Tried to reboot, reload integration etc. but result is the same.

![image](https://github.com/dolezsa/thermal_comfort/assets/55327160/5a968a8f-7c51-4203-bf5b-3bd5937e5788)
![image](https://github.com/dolezsa/thermal_comfort/assets/55327160/f0a1cf86-6acd-400b-8911-58c16274ae83)
![image](https://github.com/dolezsa/thermal_comfort/assets/55327160/38b12a6a-beb5-4732-a273-606b2ca6bc3f)

**Comment by rautesamtr** [comment]
Hi there's no sensor offered from thermal comfort that is called Temperatura, or any sensor representing the actual temperature of your sensors. There's only indices based on them. So it look like you renamed one of the indices to Temperatura?

**Comment by rautesamtr** [comment]
Also you can check the temperature the sensor uses as input in the attributes of the index sensor, e.g. 
![image](https://github.com/dolezsa/thermal_comfort/assets/1131371/0cfa8510-2916-4a28-b7a4-2903352a16f8)

**Comment by Gio-dot** [comment]
> Hi there's no sensor offered from thermal comfort that is called Temperatura, or any sensor representing the actual temperature of your sensors. There's only indices based on them. So it look like you renamed one of the indices to Temperatura?

Ok, i found where is the problem... I didn't rename any sensor, but strangely the integration named summer simmer index "Temperatura". I don't know why, but now i know that "temperatura" is summer simmer index.
Thank you.
![Immagine 2023-12-11 175217](https://github.com/dolezsa/thermal_comfort/assets/55327160/ad600a2d-8cc7-4cee-beb9-a6fad5bf7d5c)

**Comment by rautesamtr** [comment]
Found the problem. Looks like i forgott to add the summer simmer index to the new entity translation system and it automatically names it temperature because it's marked as temperature sensor. Going to fix this a soon as i have time.
