### ISSUE TITLE
Logo for home-assistant/brands

### ISSUE THREAD

**Issue by rautesamtr** [dolezsa/thermal_comfort#35]
To be accepted into hacs default repo this project needs a logo in https://github.com/home-assistant/brands for custom integration.
Attached is a suggestion for the logo. Since this is a pure homeassistant component i went with the integrations icon template and used a different color since it is a custom component. @dolezsa what do you think?

![logo](https://user-images.githubusercontent.com/1131371/145715266-9bc197e1-8e11-4389-bd32-3a4080dfebd1.png)

**Comment by dolezsa** [comment]
looks good, i likeit :thumbsup: :)

**Comment by rautesamtr** [comment]
I had to remove the house element from home assistant branding since they don't allow it for possible confusion with official integrations. I reduced it to just the central element. I hope this is still ok.

**Comment by dolezsa** [comment]
I liked the original better, but i'm still ok also with this version.
