### ISSUE TITLE
Warning since HA Update to 2024.5

### ISSUE THREAD

**Issue by anym001** [dolezsa/thermal_comfort#374]
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:190
Occurred for the first time: 07:58:32 (3 occurrences)
Last logged: 07:58:42

    Detected that custom integration 'thermal_comfort' accesses hass.helpers.service. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from service directly at custom_components/thermal_comfort/__init__.py, line 162: hass.helpers.service.async_register_admin_service(, please create a bug report at https://github.com/dolezsa/thermal_comfort/issues
    Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
    Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 630: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues

**Comment by heinemannj** [comment]
**Any news regarding pull request approval(s)?**

This integration is really useful staff - I don't want to loss it ...
