### ISSUE TITLE
Using hass.helpers.services will break TC after HA 2024.11

### ISSUE THREAD

**Issue by dagobert** [dolezsa/thermal_comfort#405]
I get a warning in my log:

`2024-10-15 11:47:10.749 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'thermal_comfort' accesses hass.helpers.service. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from service directly at custom_components/thermal_comfort/__init__.py, line 162: hass.helpers.service.async_register_admin_service(, please create a bug report at https://github.com/dolezsa/thermal_comfort/issues`

I guess if this not fixed this great component will stop working.

**Comment by dolezsa** [comment]
already fixed

**Comment by dagobert** [comment]
Sorry than, was still in 2.2.2.

Great work!
