### ISSUE TITLE
Double calculated values for absoulte humidity sensor

### ISSUE THREAD

**Issue by monotonus** [dolezsa/thermal_comfort#5]
I have an issue with the calculated absolute humidity on my balcony:

![grafik](https://user-images.githubusercontent.com/51734505/61331048-63026800-a821-11e9-9605-aed21d029f0e.png)

As you can see there are many strange spikes in the graph. These are double values in the same minute:

![grafik](https://user-images.githubusercontent.com/51734505/61331088-80cfcd00-a821-11e9-9860-fd14ee00fe94.png)
![grafik](https://user-images.githubusercontent.com/51734505/61331096-8af1cb80-a821-11e9-98d0-bb4f2c09492a.png)

I don't know why this just occurs there that often. For the indoor sensors it does'nt have these spikes. Maybe because there are not that much changes than outdoor?

![grafik](https://user-images.githubusercontent.com/51734505/61331246-ddcb8300-a821-11e9-94b1-4f5374dae9d8.png)

The sensors are all Xiaomi Temperature and Humidty sensors without pressure (the round ones). 

Any idea?

**Comment by NovDavid** [comment]
I have the same issue. I'm using the same sensor as you, via zigbee2mqtt. My theory is that hass updates the temperature and humidity values with a little time difference, but fires an update of the absolute humidity for both, hence the duplicate data points in absolute humidity, with the first being incorrect.
I didn't debug it though,so it's just a theory, and I haven't yet come up with a solution either.

**Comment by rautesamtr** [comment]
Maybe an optional poll mode could work around this. Basically sacrificing responsiveness for a smoother graph.

**Comment by rautesamtr** [comment]
Could you both give 30c551144a4ff6f9ca6d692ac4d881c62952d832 a try if using poll mode fixes the issue for you?

**Comment by rautesamtr** [comment]
Closing this for now.

**Comment by tetsuo55** [comment]
@rautesamtr the way @lymanepp solved it for me was by adding a change threshold, this way the double calculated value would be dropped and not written to the database.

Unfortunately his repo has been force pushed but i have the snippet of code here

`new_state = self._calc_simmer_danger()

        if new_state == self._state:
            return False

        if (
            isinstance(new_state, float)
            and isinstance(self._state, float)
            and abs(new_state - self._state) < self._change_threshold
        ):
            _LOGGER.debug(
                f"Suppressed {self._name} update less than {self._change_threshold} - new: {new_state} current: {self._state}",
            )
            return False`

**Comment by lymanepp** [comment]
@tetsuo55,

Now that this repo has SSI, I don't need to maintain a fork. But I restored my repo to https://github.com/lymanepp/thermal_comfort_archived.

**Comment by tetsuo55** [comment]
> @tetsuo55,
> 
> Now that this repo has SSI, I don't need to maintain a fork. But I restored my repo to https://github.com/lymanepp/thermal_comfort_archived.
Thanks
@rautesamtr is there enough information here to fix this issue in this repo?

**Comment by lymanepp** [comment]
> @rautesamtr is there enough information here to fix this issue in this repo?

@tetsuo55, have you tried using polling?

**Comment by tetsuo55** [comment]
> > @rautesamtr is there enough information here to fix this issue in this repo?
> 
> @tetsuo55, have you tried using polling?

No i don't want to switch until im sure it works because I'll lose history

**Comment by rautesamtr** [comment]
@tetsuo55 what offset did you actually use? i am looking at home assistant significant_change feature which basically sets tresholds for what is a significant change (e.g. default for °C is 0.5) but i am not sure yet how users can properly user that feature.

**Comment by lymanepp** [comment]
> @tetsuo55 what offset did you actually use? i am looking at home assistant significant_change feature which basically sets tresholds for what is a significant change (e.g. default for °C is 0.5) but i am not sure yet how users can properly user that feature.

I was using 0.1 as the threshold for changes.

**Comment by tetsuo55** [comment]
> @tetsuo55 what offset did you actually use? i am looking at home assistant significant_change feature which basically sets tresholds for what is a significant change (e.g. default for °C is 0.5) but i am not sure yet how users can properly user that feature.

I was using 0.1 but maybe 0.05 would have been better
