### ISSUE TITLE
Is there a way to specify USA or customary units?

### ISSUE THREAD

**Issue by mattlward** [dolezsa/thermal_comfort#64]
The absolute humidity presents units of g/m(cubed).

All of my other sensor units follow my system defaults of customary units.

Thanks Matt

**Comment by rautesamtr** [comment]
Not sure if it wouldn't be better if densitiy conversion would be added to [homeassistant util unit system](https://github.com/home-assistant/core/blob/dev/homeassistant/util/unit_system.py) first.

Do any other integrations convert the density unit from metric to imperial?

**Comment by mattlward** [comment]
I am not sure if there are other addons that do the conversion, but in the US that unit means very little to non-scientific persons.

**Comment by rautesamtr** [comment]
I understand your request and why it would help people with different unit system then SI to somehow better comprehend absolute humidity. Do you have a specific case where it helps you to compare the value in imperial units?

What imperial concentration unit would you expect? I checked core to see if any integrations do conversions on `*g/m³`. It looks lik only `climacell` does convert between `µg/m³` and `µg/ft³`. While `accuweather` doesn't and just keeps `µg/m³` for imperial units (So does the website).

**Comment by mattlward** [comment]
Why would it not be a absolute humidity in the real percentage of moisture in air?

**Comment by mchwalisz** [comment]
> Why would it not be a absolute humidity in the real percentage of moisture in air?

Isn't the percentage of moisture in the air a relative humidity value? The point being that amount of moisture that "fit's into" air depends on the air temparature.

**Comment by Madelena** [comment]
I'm trying to plot on a [psychrometry chart](https://drajmarsh.bitbucket.io/psychro-chart2d.html), but it requires absolute humidity in g/kg, which will not be a simple conversion of units, but involve dividing the current kg/m³ with the weight of air per m³ measured by an atmospheric pressure sensor.

**Comment by rautesamtr** [comment]
Conversion is mostly done in core now. So if there's interest in getting absolute humidity converted to us customary units an issue needs to opened there. Absolute humidity isn't an official sensor type and the `humidity` type only supports `%` as unit for now.
