### ISSUE TITLE
Units wrong for dew point using degF

### ISSUE THREAD

**Issue by lakee911** [dolezsa/thermal_comfort#66]
When I feed in a temp in degF, the value is correct but the dew point units are reported in degC.  For some reason I cannot override it in Custtomizations either.

**Comment by rautesamtr** [comment]
Hi could you provide some more info on your setup? Right now i can't reproduce this.
Thermal Comfort outputs its temperature sensors in °C but Home Assistant should outconvert it to °F if your Unit System is set to Imperial. e.g. testing with template sensors as input get the correct results in °C and °F depending on my unit setting.
![image](https://user-images.githubusercontent.com/1131371/148660014-016b1767-7fd1-4a2a-b88e-c3a2a6acd588.png)

**Comment by lakee911** [comment]
I can't reproduce it. Sorry. I suspect the problem is on my end. Probably a
database issue. I ended recreating the sensor (same data, new name) and it
worked fine. Couldn't fix the problematic one.
