### ISSUE TITLE
Dew point Different to KNX Value

### ISSUE THREAD

**Issue by hwinkel** [dolezsa/thermal_comfort#68]
HI, I have a MDT Smart Switch with temperature and humidity sensor. The Switch self calculates the Dew Point and exposes
the Temperature to the KNX bus.

To compare the Dew point of this extension, I have integrated both in a card to show the difference. The Calculation is using the same temperature and humidity sensors from the KNX switch.

![image](https://user-images.githubusercontent.com/152759/149008994-26b2b1a8-116b-4587-8fcb-dc2a386844fc.png)

Would be Great to know how big the difference might be and how t0o calibrate it?

**Comment by rautesamtr** [comment]
It's hard to tell without knowing which formula the MDT Smart Switch uses. You would have to figure that out first to compare it with the currently used one.
