### ISSUE TITLE
Feature request: Make type of generated sensors available in configuration

### ISSUE THREAD

**Issue by monotonus** [dolezsa/thermal_comfort#7]
It would be good if the four generated sensor type would be able to select while configuring the sensor on per sensor basis. As for me I just need the absolute humidity values. So for now I just commented the other three sensors out of the sensor.py to save space in the database:

SENSOR_TYPES = {
    'absolutehumidity': [DEVICE_CLASS_HUMIDITY, 'Absolute Humidity', 'g/m³']#,
    #'heatindex': [DEVICE_CLASS_TEMPERATURE, 'Heat Index', '°C'],
    #'dewpoint': [DEVICE_CLASS_TEMPERATURE, 'Dew Point', '°C'],
    #'perception': [None, 'Thermal Perception', None],
}

This means it's globally deactivated. Would be good to select them for e.g. each room.

**Comment by d3m3trius** [comment]
check https://github.com/d3m3trius/thermal_comfort

**Comment by rautesamtr** [comment]
@d3m3trius why not do a PR?
