### ISSUE TITLE
Translations not working

### ISSUE THREAD

**Issue by ahmadtawakol** [dolezsa/thermal_comfort#71]
For the Frost Risk, Thermal Perception and Simmer Zone sensors, their states are not being pulled from the translation files. Instead it just shows the string for the translation keys. I haven't seen anyone report this issue and I believe the translations were only added recently, so is this happening for me only or is it the same for everyone?

![Screen Shot 2022-01-12 at 12 06 42 PM](https://user-images.githubusercontent.com/2355493/149177573-7edfcb07-9f06-4be0-9ec4-196f5a3a48a0.png)
![Screen Shot 2022-01-12 at 12 04 59 PM](https://user-images.githubusercontent.com/2355493/149177576-07b9058e-d564-41bc-8491-6ec1300e6ed9.png)

**Comment by ahmadtawakol** [comment]
Hmm, interesting. This is the first time I come across this. I'm using the state of the sensor in a template, so it shows as `no_risk` instead of `No risk`.

Looks like there isn't a way around this either. I'll close this since this isn't a problem with this component.

**Comment by rautesamtr** [comment]
Could you post your template so i could give it a look to make sure it isn't a bug?

**Comment by ahmadtawakol** [comment]
`${states['sensor.bedroom_simmerzone'].state}`

**Comment by rautesamtr** [comment]
Looks like there's no easy solution for now other then to do custom value conversion. The problem is we use a custom device_class for the translation and template entity only accepts one of the official ones.

**Comment by ahmadtawakol** [comment]
I did find this: https://community.home-assistant.io/t/how-to-send-translation-arguments-to-the-translation-custom-integration/143965/3

I'm just not sure how to implement it.

**Comment by rautesamtr** [comment]
Thats basically what we are doing. What you are looking for is this issue: https://community.home-assistant.io/t/get-translated-entity-state-in-component-template/112721
