### ISSUE TITLE
Long-term Statistics

### ISSUE THREAD

**Issue by fredefl** [dolezsa/thermal_comfort#74]
Hi everyone,

I just installed this integration, and I really love the simplicity of the setup and all the values that it provides!

It does seem like like it's currently incompatible with the [Long-term Statistics](https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics) feature of HA. It would seem that the solution is just to set the property `state_class: measurement`.

I haven't dabbled with creating an integration yet, so I might just be naive. It would be great to able to use the statistic graphs of the Lovelace UI to keep track of absolute humidity over time.

Thank you for creating this integration!🙏

**Comment by rautesamtr** [comment]
Could you give master branch a try? It should work now.

**Comment by fredefl** [comment]
It seems to work! Adding the values to graphs now works and it does indeed indicate `state_class: measurement` on the entities in the developer entity overview.

Thank you for your great work and dedication @rautesamtr!

I hope you have wonderful weekend. ☀️
