### ISSUE TITLE
RFC: Better default icons

### ISSUE THREAD

**Issue by rautesamtr** [dolezsa/thermal_comfort#85]
# Current State
Currently thermal comfort uses the default icons provided for the corresponding device classes. For the user experience it isn't that helpful to stick to the default icons since its hard to distinguish values easily, especially if you have them in a list or in glances:
![image](https://user-images.githubusercontent.com/1131371/149655673-655a2cc1-0cfd-43ea-b1de-b9d5012bed85.png)
![image](https://user-images.githubusercontent.com/1131371/149655746-e0f6fa2f-b722-4112-bffb-b0b2b9524066.png)

While its possible that each user customizes the sensors with their own icons I think it would be great to offer better default icons as default. This could be achieved by either selecting one from the [existing material icons](https://materialdesignicons.com/) or if none is available, try to upstream one.

# List of current sensors and possible icons (this list will be updated with suggestions):
## Humidity Based
<img src="https://raw.githubusercontent.com/Templarian/MaterialDesign/master/svg/water-percent.svg" width="32"/>

### Absolute Humidity
The percent symbol doesn't really make sense for a `g/m³ value`. Personally I switched to the water drop symbol without the percent to easily distinguish between them both.
<img src="https://raw.githubusercontent.com/Templarian/MaterialDesign/master/svg/water.svg" width="32"/>

## Temperature based
<img src="https://raw.githubusercontent.com/Templarian/MaterialDesign/master/svg/thermometer.svg" width="32"/>
Most of the temperature based icons could combine the thermometer icon with a corresponding smaller icon representing that specific value. For example like the following one with a bluetooth icon.
<img src="https://raw.githubusercontent.com/Templarian/MaterialDesign/master/svg/thermometer-bluetooth.svg" width="32"/>

### Heat Index
We could just add the fire symbol to represent heat.
<img src="https://raw.githubusercontent.com/Templarian/MaterialDesign/master/svg/fire.svg" width="32"/><img src="https://raw.githubusercontent.com/rautesamtr/hass-thermal-comfort-icons/master/svg/thermometer-fire.svg" width="32"/>

### Dew Point
I think the following could be a great candidate to be added to the thermostat as a dew symbol.
<img src="https://raw.githubusercontent.com/Templarian/MaterialDesign/master/svg/water.svg" width="32"/><img src="https://raw.githubusercontent.com/rautesamtr/hass-thermal-comfort-icons/master/svg/thermometer-water.svg" width="32"/>

### Frost Point
We could add the snowflake to the thermostat for frost.
<img src="https://raw.githubusercontent.com/Templarian/MaterialDesign/master/svg/snowflake.svg" width="32"/><img src="https://raw.githubusercontent.com/rautesamtr/hass-thermal-comfort-icons/master/svg/thermometer-snowflake.svg" width="32"/>

### Simmer Index
Opposed to the heat index the simmer index is meant for the night and is probably mostly used for sleeping comfort.
We could add a moon symbol for night.
<img src="https://raw.githubusercontent.com/Templarian/MaterialDesign/master/svg/power-sleep.svg" width="32"/><img src="https://raw.githubusercontent.com/Templarian/MaterialDesign/master/svg/moon-waning-crescent.svg" width="32"/><img src="https://raw.githubusercontent.com/Templarian/MaterialDesign/master/svg/weather-night.svg" width="32"/><img src="https://raw.githubusercontent.com/rautesamtr/hass-thermal-comfort-icons/master/svg/thermometer-power-sleep.svg" width="32"/>

## Custom based
<img src="https://raw.githubusercontent.com/Templarian/MaterialDesign/master/svg/eye.svg" width="32"/>

### Thermal Perception
This one and simmer are the most difficult for me to suggest an alternate icon. Maye combine the eye icon with another one? But we don't really perceive this with our eyes do we?
Here's two attempts, one with the eye for perception and one with a hand since as humans we often use our hands to actively perceive the temperature of something.
<img src="https://raw.githubusercontent.com/rautesamtr/hass-thermal-comfort-icons/master/svg/home-thermometer-eye.svg" width="32"/><img src="https://raw.githubusercontent.com/rautesamtr/hass-thermal-comfort-icons/master/svg/hand-thermometer.svg" width="32"/><img src="https://raw.githubusercontent.com/rautesamtr/hass-thermal-comfort-icons/master/svg/human-male-thermometer.svg" width="32"/>

### Frost Risk
A snowflake isn't the same as frost but I still think this icon should work.
<img src="https://raw.githubusercontent.com/Templarian/MaterialDesign/master/svg/snowflake-alert.svg" width="32"/>

### Simmer Zone
Similar problem as Thermal Perception.
Same two attempts as for thermal perception but with a moon added.
<img src="https://raw.githubusercontent.com/rautesamtr/hass-thermal-comfort-icons/master/svg/home-thermometer-eye-power-sleep.svg" width="32"/><img src="https://raw.githubusercontent.com/rautesamtr/hass-thermal-comfort-icons/master/svg/hand-thermometer-power-sleep.svg" width="32"/><img src="https://raw.githubusercontent.com/rautesamtr/hass-thermal-comfort-icons/master/svg/human-male-thermometer-power-sleep.svg" width="32"/>

**Comment by rautesamtr** [comment]
alterntive Glances 1:
![image](https://user-images.githubusercontent.com/1131371/149661276-2e1faeac-4b4d-476c-ab78-fe89f1fed920.png)
alterntive Glances 2:
![image](https://user-images.githubusercontent.com/1131371/149661286-ecc0aff0-3acd-4ba8-8457-24e5a638fa95.png)

**Comment by rautesamtr** [comment]
![image](https://user-images.githubusercontent.com/1131371/150200128-68e09564-746d-4932-b1a9-122fe82d95d2.png)

**Comment by rautesamtr** [comment]
So the following is my latest iteration:
![image](https://user-images.githubusercontent.com/1131371/150372168-b21c521a-05e6-4070-a2f9-c2ac3e9ef05c.png)

Personally i am still not 100% sure about the thermal perception and simmer zone icon. But the limited feedback i got told me it was ok.

So the next steps I'd take would be to implement the as frontend integration ([already done](https://github.com/rautesamtr/thermal_comfort_icons)) and add a config option to enable the custom icons e.g.
```yaml
thermal_comfort
  custom_icons: true
  - sensor:
    - name: livingroom
      friendly_name: Living Room
      temperature_sensor: sensor.temperature_livingroom
      humidity_sensor: sensor.humidity_livingroom
```

**Comment by dolezsa** [comment]
my favorite is version with a little man instead of hand... i think, we should vote. :)

**Comment by rautesamtr** [comment]
I actually dropped that one 🙈. But no problem, i do all variants i have for the hand icon and add it to the icon repo so people can give them a try. Any changes can now be found here: https://github.com/rautesamtr/thermal_comfort_icons.

**Comment by rautesamtr** [comment]
@dolezsa i added the icons with the little man to the icon pack as well as icon picker support

**Comment by rautesamtr** [comment]
https://github.com/Templarian/MaterialDesign/issues/6434

**Comment by rautesamtr** [comment]
`custom_icons options` is merged and will be available with the next release.
So we should vote which of the perception icons we should use as default when the icon set is enabled.
@dolezsa @IATkachenko @papo-o @ahmadtawakol
What's your opinion? Hand or human?
![image](https://user-images.githubusercontent.com/1131371/151565949-d99d2444-35b8-4dd1-9c10-29168236e728.png)

**Comment by IATkachenko** [comment]
None of them telling something for me as icon.
Human icon looks like `body temperature` or `fells like temperature` icon for me.
Hand is harder for understanding/recognize.

**Comment by rautesamtr** [comment]
Thx everyone. Changed to the little man ;)
